name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - run: chmod +x ./gradlew
      - run: ./gradlew build --stacktrace
      - uses: actions/upload-artifact@v7
        if: success()
        with:
          name: Regrowth-fabric-26.3
          path: build/libs/*.jar
